site: GroupUnknown™
url: https://groupunknown.com
title: GroupUnknown™
description: Network S.A.
tagline: Blog dedicado à assuntos diversos
lang: pt_BR
author: groupunknown
google_analytics: UA-120280297-1

webmaster_verifications:
  google: BHhjherZoAFIqjGDO05JmCzgLmKjOIr-pD8N7TYvkg8
  #bing: 
  #alexa: 
  #yandex: 
  #baidu: 

# ["w92","w154","w185","w342","w500","w780","original"]
# https://www.themoviedb.org/talk/53c11d4ec3a3684cf4006400
article_size_img_home: w154
article_size_img_post: w185

donator_status: false

encrypt_status: false
encrypt_key: sua_chave
encrypt_url_redirect: https://groupunknown.com/?url=
encrypt_urls_bases:
  - google.com
  - mega.nz
  - mega.io
  - 1fichier.com
  - uptobox.com
  - ul.to
  - uploaded.net
  - brupload.net
  - brfiles.com
  - magnet:?xt
  - magnet:?xt=urn:btih
  - magnet

baseurl: ""
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:name #/:categories/:name
  posts:
    output: true
    permalink: /:slug #/:year/:month/:day/:slug

defaults:
  - scope:
      path: "_posts/filmes"
      type: posts
    values:
      permalink: filmes/:title
  - scope:
      path: "_posts/series"
      type: posts
    values:
      permalink: series/:title

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: /page/:num/