site: GroupUnknown™
url: https://groupunknown.com
title: GroupUnknown™
description: Network S.A.
tagline: Blog dedicado à assuntos diversos
lang: pt_BR
author: groupunknown
google_analytics: UA-120280297-1

webmaster_verifications:
  google: BHhjherZoAFIqjGDO05JmCzgLmKjOIr-pD8N7TYvkg8
  #bing: 
  #alexa: 
  #yandex: 
  #baidu: 

encrypt_status: false
encrypt_key: sua_chave
encrypt_url_redirect: https://groupunknown.com/?url=
encrypt_urls_bases:
  - google.com
  - mega.nz
  - mega.io
  - 1fichier.com
  - uptobox.com
  - ul.to
  - uploaded.net
  - brupload.net
  - brfiles.com
  - magnet:?xt
  - magnet:?xt=urn:btih
  - magnet

baseurl: ""
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:name #/:categories/:name
  posts:
    output: true
    permalink: /:slug #/:year/:month/:day/:slug

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: /page/:num/