---
title: GroupUnknown™
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
    permalink: "/donate/:path/"
  uploads:
    title: Uploads
    output: false
  without-plugin:
    title: Without Plugin
    output: true
    permalink: "/without-plugin/:path/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: without-plugin
  values:
    layout: without-plugin-item
- scope:
    path: ''
    type: products
  values:
    layout: product
description: 'GroupUnknown™ Network S.A.'

# Tracker
analytics: UA-120280297-1 # Google Analytics
google_ad_client: # Google AdSense

url: https://groupunknown.org
permalink: "/blog/:title/"
facebook_url: https://www.facebook.com/groupunknown
twitter_url: https://twitter.com/groupunknown
linkedin_url: 
googleplus_url: 
pinterest_url: 
instagram_url: 
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
input_types:
- text
- textarea
- email
- date
- checkbox
- radio
- number
- submit
form_engines:
- cloudcannon
- formspree
- formbucket
