url: https://groupunknown.com
name: groupunknown
title: GroupUnknown™
description: Network S.A.

google_analytics: UA-120280297-1

webmaster_verifications:
  google: BHhjherZoAFIqjGDO05JmCzgLmKjOIr-pD8N7TYvkg8
  #bing: 
  #alexa: 
  #yandex: 
  #baidu: 

baseurl: ""
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:name #/:categories/:name
  posts:
    output: true
    permalink: /:slug #/:year/:month/:day/:slug

#permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
