site: GroupUnknown™
url: https://groupunknown.com
title: GroupUnknown™
description: Network S.A.
tagline: Downloads de filmes e séries em 1080p & 720p
lang: pt_BR

social_facebook: groupunknown
social_twitter: 
social_instagram: 
#twitter:
  #username: 
  #card: summary
#facebook:
  #app_id: 
  #publisher: 
  #admins:

permalink: pretty
baseurl: ""

google_analytics: UA-120280297-1

webmaster_verifications:
  google: BHhjherZoAFIqjGDO05JmCzgLmKjOIr-pD8N7TYvkg8
  #bing: 
  #alexa: 
  #yandex: 
  #baidu: 

highlighter: rouge
markdown: kramdown
kramdown:
  html_to_native: true
  auto_ids: false

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name #/:categories/:name
  posts:
    output: true
    permalink: /:slug #/:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/default-card.webp
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      image: /assets/images/default-card.webp
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /assets/images/default-card.webp

paginate: 10
paginate_path: /page:num/