site: GroupUnknown™
url: https://groupunknown.com
title: GroupUnknown™
description: Network S.A.
google_analytics: UA-120280297-1
social_facebook: groupunknown
social_twitter: #yourpagename
social_instagram: #yourpagename
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: ""

webmaster_verifications:
  google: BHhjherZoAFIqjGDO05JmCzgLmKjOIr-pD8N7TYvkg8

highlighter: rouge

markdown: kramdown
kramdown:
  html_to_native: true
  auto_ids: false

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name #/:categories/:name
  posts:
    output: true
    permalink: /:slug #/:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

paginate: 10
paginate_path: /page:num/