site: GroupUnknown™
url: https://groupunknown.com
title: GroupUnknown™
description: Download de Filmes & Séries em 1080p & 720p
tagline: Download de Filmes, Séries, Músicas, Jogos, Livros e muito mais...
lang: pt_BR
author: groupunknown
google_analytics: UA-120280297-1
google_analytics_status: false

social:
  name: Agregador
  links:
    - https://twitter.com/
    - https://www.facebook.com/

webmaster_verifications:
  google: BHhjherZoAFIqjGDO05JmCzgLmKjOIr-pD8N7TYvkg8
  #bing: 
  #alexa: 
  #yandex: 
  #baidu: 

# ["w92","w154","w185","w342","w500","w780","original"]
# https://www.themoviedb.org/talk/53c11d4ec3a3684cf4006400
article_size_img_home: w154
article_size_img_post: w185

encrypt_status: false
encrypt_key: sua_chave
encrypt_url_redirect: https://groupunknown.com/?url=
encrypt_urls_bases:
  - google.com
  - mega.nz
  - mega.io
  - 1fichier.com
  - uptobox.com
  - ul.to
  - uploaded.net
  - brupload.net
  - brfiles.com
  - magnet:?xt
  - magnet:?xt=urn:btih
  - magnet

baseurl: ""
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:name #/:categories/:name
  posts:
    output: true
    permalink: /:slug #/:year/:month/:day/:slug
  downloads:
    output: true # https://ognjen.io/generating-json-in-jekyll/

# https://talk.jekyllrb.com/t/creating-custom-permalinks-for-each-post-category/434/5
defaults:
  - scope:
      path: "_posts/filmes"
      type: posts
    values:
      permalink: filmes/:slug
      layout: post
  - scope:
      path: "_posts/series"
      type: posts
    values:
      permalink: series/:slug
      layout: post
  - scope:
      path: "_posts/musicas"
      type: posts
    values:
      permalink: musicas/:slug
      layout: post
  - scope:
      path: "_posts/jogos"
      type: posts
    values:
      permalink: jogos/:slug
      layout: post
  - scope:
      path: "_posts/livros"
      type: posts
    values:
      permalink: livros/:slug
      layout: post
  - scope:
      path: "_posts/blog"
      type: posts
    values:
      permalink: blog/:slug
      layout: post
  - scope:
      path: "_downloads/filmes"
      type: downloads
    values:
      permalink: filmes/:slug/downloads
      layout: downloads
  - scope:
      path: "_downloads/series"
      type: downloads
    values:
      permalink: series/:slug/downloads
      layout: downloads

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10
paginate_path: /page/:num/
